language: ruby
rvm:
  - 2.6.5
cache: bundler
bundler_args: --without production --deployment
addons:
  postgresql: "9.6"
  chrome: stable
before_install:
  - gem update --system
  - gem install bundler --pre
before_script:
  - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start && sleep 3
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
script: bundle exec rspec
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c57bd85cc9e2aba2d679
    on_success: change
    on_failure: always
    on_start: false

